// Generated by gencpp from file stdr_msgs/MoveBox.msg
// DO NOT EDIT!


#ifndef STDR_MSGS_MESSAGE_MOVEBOX_H
#define STDR_MSGS_MESSAGE_MOVEBOX_H

#include <ros/service_traits.h>


#include <stdr_msgs/MoveBoxRequest.h>
#include <stdr_msgs/MoveBoxResponse.h>


namespace stdr_msgs
{

struct MoveBox
{

typedef MoveBoxRequest Request;
typedef MoveBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveBox
} // namespace stdr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stdr_msgs::MoveBox > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::stdr_msgs::MoveBox&) { return value(); }
};

template<>
struct DataType< ::stdr_msgs::MoveBox > {
  static const char* value()
  {
    return "stdr_msgs/MoveBox";
  }

  static const char* value(const ::stdr_msgs::MoveBox&) { return value(); }
};


// service_traits::MD5Sum< ::stdr_msgs::MoveBoxRequest> should match 
// service_traits::MD5Sum< ::stdr_msgs::MoveBox > 
template<>
struct MD5Sum< ::stdr_msgs::MoveBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stdr_msgs::MoveBox >::value();
  }
  static const char* value(const ::stdr_msgs::MoveBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stdr_msgs::MoveBoxRequest> should match 
// service_traits::DataType< ::stdr_msgs::MoveBox > 
template<>
struct DataType< ::stdr_msgs::MoveBoxRequest>
{
  static const char* value()
  {
    return DataType< ::stdr_msgs::MoveBox >::value();
  }
  static const char* value(const ::stdr_msgs::MoveBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stdr_msgs::MoveBoxResponse> should match 
// service_traits::MD5Sum< ::stdr_msgs::MoveBox > 
template<>
struct MD5Sum< ::stdr_msgs::MoveBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stdr_msgs::MoveBox >::value();
  }
  static const char* value(const ::stdr_msgs::MoveBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stdr_msgs::MoveBoxResponse> should match 
// service_traits::DataType< ::stdr_msgs::MoveBox > 
template<>
struct DataType< ::stdr_msgs::MoveBoxResponse>
{
  static const char* value()
  {
    return DataType< ::stdr_msgs::MoveBox >::value();
  }
  static const char* value(const ::stdr_msgs::MoveBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STDR_MSGS_MESSAGE_MOVEBOX_H
